typography_spectrum: 0.1603085605893284
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15454582776874304
  lightness: 0.9726778801996261
  saturation: 0.6695683877915144
  rhythmicContrast: 0.06184831354767084
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39441353641450405
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Brad Pearce
  email: brad@bepearcelaw.com
name: PearceLawPLLC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
